### ISSUE TITLE
Implement AutoModel

### ISSUE THREAD

**Issue by mpariente** [asteroid-team/asteroid#379]
When should probably have `AutoModel` in asteroid. 
`transformers` 

We're moving our models to HuggingFace's model hub, and the `Use in Asteroid` snippet doesn't adapt to the model type. 

See [here](https://huggingface.co/mpariente/ConvTasNet_WHAM_sepclean) for an example. The `Use in Asteroid` suggests to load with DPRNNTasNet whereas the model in ConvTasNet. 
![image](https://user-images.githubusercontent.com/18496796/101387432-b5cd3b80-38be-11eb-9bd4-9759e0eb6773.png)
 
This actually works, because `BaseModel` with look for the registered models, but we should make things more explicit by calling it `AutoModel`. I didn't look at their implementation yet but I thought it might be good to discuss it anyway.

**Comment by jonashaag** [comment]
How about making it an actual function, not a (class)method, since the loader code doesn't actually make use of the class hierarchy?

```
from asteroid import load_pretrained
```

@julien-c is there a particular reason you use an empty `AutoTokenizer` class for `from_pretrained` rather than making it a simple function? Is it for consistency with `ConcreteModel.from_pretrained`?

**Comment by julien-c** [comment]
Yes, on our side mostly a stylistic preference.

**Comment by mpariente** [comment]
Ok, that's also possible. Do you have arguments against the classmethod and in favour of the function?

**Comment by jonashaag** [comment]
Not really. Maybe actually slightly in favour of the classmethod because consistency.

**Comment by mpariente** [comment]
Keeping `BaseModel`, we'll see later if we need better.
