### ISSUE TITLE
Question: why No module named 'mnodel'?

### ISSUE THREAD

**Issue by Wzw666888** [asteroid-team/asteroid#512]
Hello，i wrote a model of my own with the help of your framework, but encountered some problems. The third stage has been completed, and I successfully got a pth model file. I want to enter the fourth stage to evaluate the model, it will return a ‘keyerror‘ error, I don't know how to modify this problem. Then I want to skip this step and use the trained model to separate the sound source. An error also occurred. I think I might have inherited some functions less when creating my own model. Please give me a little help. Below are some screenshots of the problems.
![image](https://user-images.githubusercontent.com/82068553/120984780-89cb3e00-c7ad-11eb-93de-5f1b66cf88f2.png)
![image](https://user-images.githubusercontent.com/82068553/120984984-c0a15400-c7ad-11eb-9a3e-9a2e6502a993.png)

You worked hard, thank you.

**Comment by Wzw666888** [comment]
please help me.

**Comment by jonashaag** [comment]
Just a guess: The code that registers your model with Asteroid is only run in the training script (because you import the code that runs `register_model`). You need to make sure the code is imported whenever you want to access the model. For `eval.py` it's obvious, just add an import. For `asteroid-infer`, I'm not sure how to solve it in an elegant way but you can just place your import in the `asteroid-infer` source code as a hack.

**Comment by Wzw666888** [comment]
Thanks, I have solved it.
